# Generated by Django 2.2.2 on 2019-06-29 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20190629_1313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='genre',
            new_name='gener',
        ),
    ]
