# Generated by Django 2.2.2 on 2019-07-01 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20190629_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_song',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
